const List<String> surgicalProcedures = [
  "Colecistectomia videolaparoscópica",
  "Hérnia inguinal direita",
  "Hérnia inguinal esquerda",
  "Hérnia inguinal bilateral",
  "Hérnia inguinal direita videolaparoscópica",
  "Hérnia inguinal esquerda videolaparoscópica",
  "Hérnia inguinal bilateral videolaparoscópica",
  "Hernioplastia umbilical",
  "Hernioplastia umbilical videolaparoscópica",
  "Hernioplastia incisional",
  "Hernioplastia incisional videolaparoscópica",
  "Hernioplastia crural direita",
  "Hernioplastia crural esquerda",
  "Hernioplastia crural bilateral",
  "Hernioplastia crural direita videolaparoscópica",
  "Hernioplastia crural esquerda videolaparoscópica",
  "Hernioplastia crural bilateral videolaparoscópica",
  "Histerectomia total",
  "Histerectomia videolaparoscópica",
  "Hemorroidectomia",
  "Salpingectomia direita",
  "Salpingectomia esquerda",
  "Salpingectomia bilateral",
  "Mastectomia direita",
  "Mastectomia esquerda",
  "Mastectomia bilateral",
  "Quadrantectomia direita",
  "Quadrantectomia esquerda",
  "Biópsia de linfonodo sentinela direita",
  "Biópsia de linfonodo sentinela esquerda",
  "Colectomia total",
  "Colectomia direita",
  "Colectomia esquerda",
  "Colectomia videolaparoscópica",
  "Retossigmoidectomia",
  "Amputação do reto",
  "Prostatectomia",
  "Nefrolitotomia percutânea direita",
  "Nefrolitotomia percutânea esquerda",
  "Flebectomia direita",
  "Flebectomia esquerda",
  "Flebectomia bilateral",
  "Correção de aneurisma aórtico",
  "Tireoidectomia parcial direita",
  "Tireoidectomia parcial esquerda",
  "Tireoidectomia total",
  "Criação de fístula arteriovenosa direita",
  "Criação de fístula arteriovenosa esquerda",
  "Lobectomia pulmonar direita",
  "Lobectomia pulmonar esquerda",
  "Pneumonectomia",
  "Ooforectomia direita",
  "Ooforectomia esquerda",
  "Ooforectomia bilateral",
  "Excisão de endometriose",
  "Abdominoplastia",
  "Excisão de tumor de partes moles",
  "Gastrectomia total",
  "Gastrectomia parcial",
  "Gastrectomia videolaparoscópica",
  "Revascularização de membros inferiores",
  "Desbridamento cirúrgico",
  "Amputação de pododáctilo direito",
  "Amputação de pododáctilo esquerdo",
  "Amputação de antepé direito",
  "Amputação de antepé esquerdo",
  "Amputação infrapatelar direita",
  "Amputação infrapatelar esquerda",
  "Amputação suprapatelar direita",
  "Amputação suprapatelar esquerda"
];
